// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: plugin/executable/cache/dump.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CachedEntry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Key                 []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Msg                 []byte                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CacheExpirationTime int64                  `protobuf:"varint,3,opt,name=cache_expiration_time,json=cacheExpirationTime,proto3" json:"cache_expiration_time,omitempty"`
	MsgExpirationTime   int64                  `protobuf:"varint,4,opt,name=msg_expiration_time,json=msgExpirationTime,proto3" json:"msg_expiration_time,omitempty"`
	MsgStoredTime       int64                  `protobuf:"varint,5,opt,name=msg_stored_time,json=msgStoredTime,proto3" json:"msg_stored_time,omitempty"`
	DomainSet           string                 `protobuf:"bytes,6,opt,name=domain_set,json=domainSet,proto3" json:"domain_set,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CachedEntry) Reset() {
	*x = CachedEntry{}
	mi := &file_plugin_executable_cache_dump_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedEntry) ProtoMessage() {}

func (x *CachedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_executable_cache_dump_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedEntry.ProtoReflect.Descriptor instead.
func (*CachedEntry) Descriptor() ([]byte, []int) {
	return file_plugin_executable_cache_dump_proto_rawDescGZIP(), []int{0}
}

func (x *CachedEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CachedEntry) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CachedEntry) GetCacheExpirationTime() int64 {
	if x != nil {
		return x.CacheExpirationTime
	}
	return 0
}

func (x *CachedEntry) GetMsgExpirationTime() int64 {
	if x != nil {
		return x.MsgExpirationTime
	}
	return 0
}

func (x *CachedEntry) GetMsgStoredTime() int64 {
	if x != nil {
		return x.MsgStoredTime
	}
	return 0
}

func (x *CachedEntry) GetDomainSet() string {
	if x != nil {
		return x.DomainSet
	}
	return ""
}

type CacheDumpBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CachedEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheDumpBlock) Reset() {
	*x = CacheDumpBlock{}
	mi := &file_plugin_executable_cache_dump_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheDumpBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDumpBlock) ProtoMessage() {}

func (x *CacheDumpBlock) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_executable_cache_dump_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDumpBlock.ProtoReflect.Descriptor instead.
func (*CacheDumpBlock) Descriptor() ([]byte, []int) {
	return file_plugin_executable_cache_dump_proto_rawDescGZIP(), []int{1}
}

func (x *CacheDumpBlock) GetEntries() []*CachedEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_plugin_executable_cache_dump_proto protoreflect.FileDescriptor

const file_plugin_executable_cache_dump_proto_rawDesc = "" +
	"\n" +
	"\"plugin/executable/cache/dump.proto\x12\x05cache\"\xdc\x01\n" +
	"\vCachedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\fR\x03msg\x122\n" +
	"\x15cache_expiration_time\x18\x03 \x01(\x03R\x13cacheExpirationTime\x12.\n" +
	"\x13msg_expiration_time\x18\x04 \x01(\x03R\x11msgExpirationTime\x12&\n" +
	"\x0fmsg_stored_time\x18\x05 \x01(\x03R\rmsgStoredTime\x12\x1d\n" +
	"\n" +
	"domain_set\x18\x06 \x01(\tR\tdomainSet\">\n" +
	"\x0eCacheDumpBlock\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.cache.CachedEntryR\aentriesB\x19Z\x17plugin/executable/cacheb\x06proto3"

var (
	file_plugin_executable_cache_dump_proto_rawDescOnce sync.Once
	file_plugin_executable_cache_dump_proto_rawDescData []byte
)

func file_plugin_executable_cache_dump_proto_rawDescGZIP() []byte {
	file_plugin_executable_cache_dump_proto_rawDescOnce.Do(func() {
		file_plugin_executable_cache_dump_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_executable_cache_dump_proto_rawDesc), len(file_plugin_executable_cache_dump_proto_rawDesc)))
	})
	return file_plugin_executable_cache_dump_proto_rawDescData
}

var file_plugin_executable_cache_dump_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_executable_cache_dump_proto_goTypes = []any{
	(*CachedEntry)(nil),    // 0: cache.CachedEntry
	(*CacheDumpBlock)(nil), // 1: cache.CacheDumpBlock
}
var file_plugin_executable_cache_dump_proto_depIdxs = []int32{
	0, // 0: cache.CacheDumpBlock.entries:type_name -> cache.CachedEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_executable_cache_dump_proto_init() }
func file_plugin_executable_cache_dump_proto_init() {
	if File_plugin_executable_cache_dump_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_executable_cache_dump_proto_rawDesc), len(file_plugin_executable_cache_dump_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_executable_cache_dump_proto_goTypes,
		DependencyIndexes: file_plugin_executable_cache_dump_proto_depIdxs,
		MessageInfos:      file_plugin_executable_cache_dump_proto_msgTypes,
	}.Build()
	File_plugin_executable_cache_dump_proto = out.File
	file_plugin_executable_cache_dump_proto_goTypes = nil
	file_plugin_executable_cache_dump_proto_depIdxs = nil
}
